### ISSUE TITLE
h5ad to Seurat conversion "AttributeError: 'dict' object has no attribute 'dtype'"

### ISSUE THREAD

**Issue by jestlin15** [cellgeni/sceasy#77]
Hi, I am trying to convert a h5ad file to Seurat object but am faced with this error can I please please get some help. 

This is my inout code : 
sceasy::convertFormat("GSE175533_sceasy_hay.h5ad", from="anndata", to="seurat",
                       outFile='GSE175533_sceasy_hay.rds')

Python Exception Message ────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "~/python3.9/site-packages/anndata/readwrite/read.py", line 447, in read_h5ad
  File "~/python3.9/site-packages/anndata/readwrite/read.py", line 502, in _read_args_from_h5ad
  File "~/python3.9/site-packages/anndata/core/anndata.py", line 2157, in _args_from_dict
AttributeError: 'dict' object has no attribute 'dtype'

── R Traceback ────────────────────────────────────────────────────────────
    ▆
 1. └─sceasy::convertFormat(...)
 2.   └─sceasy (local) func(obj, outFile = outFile, main_layer = main_layer, ...)
 3.     └─anndata$read_h5ad(inFile)
 4.       └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)

R version 4.1.2

GSE h5ad Data download from : https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE175533

**Comment by lisch7** [comment]
same issue

**Comment by TamiaChin** [comment]
This is an issue concerning anndata package.
conda install "anndata>=0.7" -c conda-forge
It should fix
